/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_des_capteurs (void);
GtkWidget* create_window_ajouter (void);
GtkWidget* create_window_consulter (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_fenetre_modifier (void);
GtkWidget* create_service_main (void);
GtkWidget* create_MENU_PRINCIPAL (void);
GtkWidget* create_fenetre_stats (void);
GtkWidget* create_window1 (void);
GtkWidget* create_windowafficher (void);
GtkWidget* create_windowajouter (void);
GtkWidget* create_af (void);
GtkWidget* create_mod (void);
GtkWidget* create_aj (void);
GtkWidget* create_windowajout (void);
GtkWidget* create_windowinterf (void);
GtkWidget* create_windowmodif (void);
GtkWidget* create_windowalert (void);
GtkWidget* create_Connexion (void);
